# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CARTOUCH', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartouche',
            name='date_fichier',
        ),
    ]
