# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CARTOUCH', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartouche',
            old_name='date',
            new_name='date_fichier',
        ),
    ]
