# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARTOUCH', '0002_auto_20161219_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('info', models.CharField(max_length=250)),
                ('auteur', models.CharField(max_length=60)),
            ],
        ),
    ]
