# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARTOUCH', '0003_infos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='info',
            field=models.CharField(max_length=350),
        ),
    ]
